### ISSUE TITLE
Pip3 is not installed correctly

### ISSUE THREAD

**Issue by ciaransweet** [UKHO/vm-agent-aib#21]
When trying to run a `pip3` command, the following output is given:

```
pip3: command not found
```

I'm not convinced that `apt install` is working, would recommend switching to `apt-get install` instead. Can't try this yet due to broken builds but leaving this here as a reminder for me to raise a PR :)

**Comment by elduddz** [comment]
Python3 is certainly there, but I do have to ask for python3 specifically.

**Comment by ciaransweet** [comment]
Python3 is there yes, but that is included by default with Ubuntu1804. Pip3 is not

**Comment by MarcDenman** [comment]
Closed by #23
